<!DOCTYPE html>
<html lang="en">
<head>
    <!-- hexo-inject:begin --><!-- hexo-inject:end --><meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="google-site-verification" content="xBT4GhYoi5qRD5tr338pgPM5OWHHIDR6mNg1a3euekI" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Thinkgamer的博客">
    <meta name="keyword"  content="Python,Django,爬虫,Hadoop,Maching Learning,数据挖掘,机器学习,云计算,大数据,深度学习,开发者,程序猿,程序媛,极客,编程,代码,开源,IT网站,Developer,Programmer,Coder,用户体验">
    <link rel="shortcut icon" href="/assets/img/favicon.ico">

    <title>
        
        Python中try...except...finally的理解 - Thinkgamer的博客 | Thinkgamer&#39;s Blog
        
    </title>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="/css/aircloud.css">
    <link rel="stylesheet" href="/css/gitment.css">
    <!--<link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">-->
    <link href="//at.alicdn.com/t/font_620856_pl6z7sid89qkt9.css" rel="stylesheet" type="text/css">
    <!-- ga & ba script hoook -->
    <script></script><!-- hexo-inject:begin --><!-- hexo-inject:end -->
</head>

<body>

<!-- hexo-inject:begin --><!-- hexo-inject:end --><div class="site-nav-toggle" id="site-nav-toggle">
    <button>
        <span class="btn-bar"></span>
        <span class="btn-bar"></span>
        <span class="btn-bar"></span>
    </button>
</div>

<div class="index-about">
    <i> All In CTR、DL、ML、RL、NLP、KG </i>
</div>

<div class="index-container">
    
    <div class="index-left">
        
<div class="nav" id="nav">
    <div class="avatar-name">
        <div class="avatar ">
            <img src="/assets/img/head.jpg" />
        </div>
        <div class="name">
            <i>Thinkgamer</i>
        </div>
    </div>
    <div class="contents" id="nav-content">
        <ul>
            <li >
                <a href="/">
                    <i class="iconfont icon-shouye1"></i>
                    <span>主页</span>
                </a>
            </li>
            <li >
                <a href="/tags">
                    <i class="iconfont icon-biaoqian1"></i>
                    <span>标签</span>
                </a>
            </li>
            <li >
                <a href="/archive">
                    <i class="iconfont icon-guidang2"></i>
                    <span>存档</span>
                </a>
            </li>
            <li >
                <a href="/about/">
                    <i class="iconfont icon-guanyu2"></i>
                    <span>关于</span>
                </a>
            </li>
            
            <li>
                <a id="search">
                    <i class="iconfont icon-sousuo1"></i>
                    <span>搜索</span>
                </a>
            </li>
            
        </ul>
    </div>
    
        <div id="toc" class="toc-article">
    
</div>
    
</div>


<div class="search-field" id="search-field">
    <div class="search-container">
        <div class="search-input">
            <span id="esc-search"> <i class="icon-fanhui iconfont"></i></span>
            <input id="search-input"/>
            <span id="begin-search">搜索</span>
        </div>
        <div class="search-result-container" id="search-result-container">

        </div>
    </div>
</div>

        <div class="index-about-mobile">
            <i> All In CTR、DL、ML、RL、NLP、KG </i>
        </div>
    </div>
    
    <div class="index-middle">
        <!-- Main Content -->
        <div class="post-container">
    <div class="post-title">
        Python中try...except...finally的理解
    </div>

    <div class="post-meta">
        <span class="attr">发布于：<span>2015-01-05 23:24:00</span></span>
        
        <span class="attr">标签：/
        
        <a class="tag" href="/tags/#Python" title="Python">Python</a>
        <span>/</span>
        
        
        </span>
        <span class="attr">访问：<span id="busuanzi_value_page_pv"></span>
</span>
</span>
    </div>
    <div class="post-content no-indent">
        <p>首先我们打开一个不存在的文件：</p>
<figure class="highlight ini"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="attr">fp</span> = open(<span class="string">"null.txt"</span>,<span class="string">"r"</span>)</span><br></pre></td></tr></table></figure>
<p>然后提示报错如下：</p>
<a id="more"></a>
<figure class="highlight sql"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line">IOErro Traceback (most recent <span class="keyword">call</span> <span class="keyword">last</span>)  </span><br><span class="line">&lt;ipython-<span class="keyword">input</span><span class="number">-3</span>-f70973547c7e&gt; <span class="keyword">in</span> &lt;<span class="keyword">module</span>&gt;()  </span><br><span class="line"><span class="comment">----&gt; 1 fp = open("null.txt","r")  </span></span><br><span class="line">  </span><br><span class="line">IOError: [Errno <span class="number">2</span>] <span class="keyword">No</span> such <span class="keyword">file</span> <span class="keyword">or</span> <span class="keyword">directory</span>: <span class="string">'null.txt'</span></span><br></pre></td></tr></table></figure>
<p>接着我们使用try…except…来执行这条语句</p>
<figure class="highlight routeros"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">In</span> [4]: try:  </span><br><span class="line">   <span class="built_in">..</span>.:     fp = open(<span class="string">"null.txt"</span>,<span class="string">"r"</span>)  </span><br><span class="line">   <span class="built_in">..</span>.: except:  </span><br><span class="line">   <span class="built_in">..</span>.:     <span class="builtin-name">print</span> <span class="string">"open error"</span>  </span><br><span class="line">   <span class="built_in">..</span>.:       </span><br><span class="line">open error</span><br></pre></td></tr></table></figure>
<p>接着我们再在后面加一条finally语句，所谓的filally就是最后要执行的，它不管你前边是否发送错误<br><figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">In [<span class="number">4</span>]: <span class="keyword">try</span>:  </span><br><span class="line">   <span class="keyword">...</span>:     fp =open(<span class="string">'null.txt'</span>,<span class="string">'r'</span>)  </span><br><span class="line">   <span class="keyword">...</span>: except:  </span><br><span class="line">   <span class="keyword">...</span>:     print <span class="string">'opoen error'</span>  </span><br><span class="line">   <span class="keyword">...</span>: finally:  </span><br><span class="line">   <span class="keyword">...</span>:     print <span class="string">'end'</span>  </span><br><span class="line">   <span class="keyword">...</span>:       </span><br><span class="line">opoen error  </span><br><span class="line">end</span><br></pre></td></tr></table></figure></p>
<p>接着我们使用except打印出错误类型，然后观察错误的type</p>
<figure class="highlight vim"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">In [<span class="number">5</span>]: <span class="keyword">try</span>:  </span><br><span class="line">   ...:     fp = <span class="keyword">open</span>(<span class="string">'null.txt'</span>,<span class="string">'r'</span>)  </span><br><span class="line">   ...: except Exception,<span class="keyword">e</span>:  </span><br><span class="line">   ...:     <span class="keyword">print</span> <span class="keyword">e</span>  </span><br><span class="line">   ...:     <span class="keyword">print</span> <span class="built_in">type</span>(<span class="keyword">e</span>)  </span><br><span class="line">   ...:       </span><br><span class="line">[Errno <span class="number">2</span>] No such <span class="keyword">file</span> <span class="built_in">or</span> directory: <span class="string">'null.txt'</span>  </span><br><span class="line">&lt;<span class="built_in">type</span> <span class="string">'exceptions.IOError'</span>&gt;</span><br></pre></td></tr></table></figure>
<p>我们可以看到except把错误捕捉到赋值给e，然后将其打印出，可以看到为IOError，所以在这里我们可以修改上边为：<br><figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">In [<span class="number">9</span>]: <span class="keyword">try</span>:  </span><br><span class="line">   <span class="keyword">...</span>:     fp = open(<span class="string">'null.txt'</span>, <span class="string">'r'</span>)  </span><br><span class="line">   <span class="keyword">...</span>: except IOError,e:  </span><br><span class="line">   <span class="keyword">...</span>:     print <span class="string">"ioerror"</span>  </span><br><span class="line">   <span class="keyword">...</span>:       </span><br><span class="line">ioerror</span><br></pre></td></tr></table></figure></p>
<p>当然这里如果不是IOError的话，上边except语句是捕捉不到的，例如：</p>
<figure class="highlight routeros"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">In</span> [10]: try:  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     a = 10/0  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>: except IOError,e:  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     <span class="builtin-name">print</span> <span class="string">"ioerror"</span>  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:       </span><br><span class="line">---------------------------------------------------------------------------  </span><br><span class="line">ZeroDivisionError                         Traceback (most recent call last)  </span><br><span class="line">&lt;ipython-input-10-e17eff88239d&gt; <span class="keyword">in</span> &lt;module&gt;()  </span><br><span class="line">      1 try:  </span><br><span class="line">----&gt; 2     a = 10/0  </span><br><span class="line">      3 except IOError,e:  </span><br><span class="line">      4     <span class="builtin-name">print</span> <span class="string">"ioerror"</span>  </span><br><span class="line">      5   </span><br><span class="line">  </span><br><span class="line">ZeroDivisionError: integer division <span class="keyword">or</span> modulo by zero</span><br></pre></td></tr></table></figure>
<p>这时我们需要另外的错误类型进行捕获，例如：<br><figure class="highlight routeros"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">In</span> [11]: try:  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     a = 10/0  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>: except IOError,e:  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     <span class="builtin-name">print</span> <span class="string">"IOError"</span>  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>: except ZeroDivisionError,e:  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     <span class="builtin-name">print</span> <span class="string">"Zero Error"</span>  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:       </span><br><span class="line">Zero Error</span><br></pre></td></tr></table></figure></p>
<p>可以看到第一个except并没有捕捉到错误，所以传给下一个except，当然如果所有的except都没有捕获到的话，程序就会抛出异常<br>在这里我们不得不注意的是，python的错误类型其实都是class，所有的错误类型都继承自BaseException，所以在使用except时需要注意的是，它不但捕获该类型的错误，还把其子类也“一网打尽”。比如：<br><figure class="highlight clean"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">In [<span class="number">14</span>]: try:  </span><br><span class="line">   ....:     a = <span class="number">10</span> /<span class="number">0</span>  </span><br><span class="line">   ....: except StandardError,e:  </span><br><span class="line">   ....:     print <span class="string">'standardError'</span>  </span><br><span class="line">   ....: except ZeroDivisionError,e:  </span><br><span class="line">   ....:     print <span class="string">'zero error'</span>  </span><br><span class="line">   ....:       </span><br><span class="line">standardError</span><br></pre></td></tr></table></figure></p>
<p>第二个except永远也捕获不到ValueError，因为ZeroDivisionError是StandardError的子类，如果有，也被第一个except给捕获了。<br>使用try…except…finally的另外一个好处是，可以跨越多层调用，例如：</p>
<figure class="highlight routeros"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">In</span> [15]: def foo(m):  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     return 10/int(m)  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:   </span><br><span class="line">  </span><br><span class="line"><span class="keyword">In</span> [16]: def goo():  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     a = <span class="string">"0"</span>  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     foo(a)  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:       </span><br><span class="line">  </span><br><span class="line"><span class="keyword">In</span> [17]: def main():  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     goo()  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:       </span><br><span class="line">  </span><br><span class="line"><span class="keyword">In</span> [18]: try:  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     main()  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>: except Exception,e:  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:     <span class="builtin-name">print</span> e  </span><br><span class="line">   <span class="built_in">..</span><span class="built_in">..</span>:       </span><br><span class="line">integer division <span class="keyword">or</span> modulo by zero</span><br></pre></td></tr></table></figure>
<p>在foo()函数中抛出的错误，然而在goo和main函数中都没有进行捕捉，在执行main函数时进行捕获，也可以捕获到</p>
<p>除了try…except…finally之外还有python的logging模块，也可以进行错误调试，当然我们也可以使用raise抛出异常</p>
<hr>
<center>
    <img src="http://img.blog.csdn.net/20171231111930492?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvR2FtZXJfZ3l0/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast">
    <br>
打开微信扫一扫，关注公众号【搜索与推荐Wiki】
</center>
        
            <div class="donate-container">
    <div class="donate-button">
        <button id="donate-button">赞赏</button>
    </div>
    <div class="donate-img-container hide" id="donate-img-container">
        <img id="donate-img" src="" data-src="/assets/img/weixin.jpeg">
        <p> 你的支持是我进步的最大动力！ </p>
    </div>
</div>
        
        <br />
        <div id="comment-container">
        </div>
        <div id="disqus_thread"></div>

        <div id="lv-container">
        </div>

    </div>
</div>
    </div>
</div>


<footer class="footer">
    <ul class="list-inline text-center">
        
        
        <li>
            <a target="_blank" href="https://www.zhihu.com/people/thinkgamer">
                            <span class="fa-stack fa-lg">
                                 <i class="iconfont icon-zhihu"></i>
                            </span>
            </a>
        </li>
        

        
        <li>
            <a target="_blank" href="http://weibo.com/5352480017">
                            <span class="fa-stack fa-lg">
                                  <i class="iconfont icon-weibo"></i>
                            </span>
            </a>
        </li>
        

        

        
        <li>
            <a target="_blank"  href="https://github.com/thinkgamer">
                            <span class="fa-stack fa-lg">
                                <i class="iconfont icon-github"></i>
                            </span>
            </a>
        </li>
        


        

    </ul>
    
    <p>
        <span id="busuanzi_container_site_pv">
            <span id="busuanzi_value_site_pv"></span>PV
        </span>
        <span id="busuanzi_container_site_uv">
            <span id="busuanzi_value_site_uv"></span>UV
        </span>
        || Created By <a href="https://blog.csdn.net/gamer_gyt">Thinkgamer</a></p>
</footer><!-- hexo-inject:begin --><!-- hexo-inject:end -->




</body>

<script>
    // We expose some of the variables needed by the front end
    window.hexo_search_path = "search.json"
    window.hexo_root = "/"
    window.isPost = true
</script>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="/js/index.js"></script>
<script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>




</html>
